spring:
  application:
    name: coupon-service
server:
  port: 8085
  servlet:
    context-path: /couponapp
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        exclude:
        - "*"